/**
 *
 * $Id$
 */
package pt.iscte.osgi.viscte.model.validation;


/**
 * A sample validator interface for {@link pt.iscte.osgi.viscte.model.Lifecycle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LifecycleValidator {
	boolean validate();

	boolean validateStart(long value);
	boolean validateEnd(long value);
}
